# Generated by Django 4.2.7 on 2023-12-01 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True, verbose_name='Nombre categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=500, verbose_name='Nombre y Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('username', models.CharField(default='cliente', max_length=16, verbose_name='username')),
                ('password', models.CharField(default='cliente1234', max_length=16, verbose_name='password')),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=250, verbose_name='Nombre y apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('tipo_de_consulta', models.IntegerField(choices=[('', '-Seleccione-'), (1, 'Información sobre productos'), (2, 'Tengo problemas con mi compra'), (3, 'Cambio o devolucion')], verbose_name='Tipo de consulta')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha y hora')),
                ('se_envio_email', models.BooleanField(default=False, verbose_name='se_envio_email')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.categorias')),
            ],
        ),
    ]
