# Generated by Django 4.2.7 on 2023-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_apellido',
            field=models.CharField(max_length=500, verbose_name='Nombre Apellido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_de_consulta',
            field=models.IntegerField(choices=[('', '-Seleccione-'), (1, 'Informacion sobre productos'), (2, 'Tengo problemas con mi compra'), (3, 'Cambio o devolucion')], verbose_name='Tipo de consulta'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
