# Generated by Django 4.2.7 on 2023-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_cliente_nombre_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre_y_apellido',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default='Apellido por defecto', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=250, verbose_name='Nombre'),
        ),
    ]
