# Generated by Django 4.2.7 on 2023-12-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_contacto_nombre_y_apellido_contacto_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre_y_apellido',
            field=models.CharField(default=2, max_length=250, verbose_name='Nombre y apellido'),
            preserve_default=False,
        ),
    ]
