# Generated by Django 4.2.7 on 2023-12-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_contacto_apellido_remove_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selectfechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha final ')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='se_envio_email',
        ),
    ]
