# Generated by Django 4.2.7 on 2023-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_genealogista_gestor_delete_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre_y_apellido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_de_consulta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default='Usuario Apellido', max_length=250, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='Usuario nombre', max_length=250, verbose_name='Nombre'),
        ),
    ]
