# Generated by Django 4.2.7 on 2023-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_contacto_nombre_y_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='email',
        ),
        migrations.AddField(
            model_name='contacto',
            name='mail',
            field=models.EmailField(default='Mail defecto', max_length=250, verbose_name='Mail'),
        ),
    ]
