# Generated by Django 4.2.2 on 2023-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_contacto_email_contacto_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name_plural': 'Gestores'},
        ),
        migrations.AlterField(
            model_name='genealogista',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='nombre_gestoria',
            field=models.CharField(max_length=100, verbose_name='nombre_gestoria'),
        ),
    ]
