# Generated by Django 4.2.2 on 2023-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_gestor_options_alter_genealogista_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genealogista',
            name='servicios',
            field=models.CharField(default='Servicios informados', max_length=200, verbose_name='servicios'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='servicios',
            field=models.CharField(default='Servicios informados', max_length=200, verbose_name='servicios'),
        ),
    ]
