# Generated by Django 4.2.2 on 2023-12-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_genealogista_servicios_gestor_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genealogista',
            options={'verbose_name_plural': 'Genealogistas'},
        ),
        migrations.AlterField(
            model_name='genealogista',
            name='nombre_genealogista',
            field=models.CharField(max_length=100, verbose_name='nombre_genealogista'),
        ),
    ]
