# Generated by Django 4.2.2 on 2023-12-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_genealogista_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('sitio_web', models.CharField(default='website', max_length=100, verbose_name='sitio web')),
                ('servicios', models.CharField(default='Servicios informados', max_length=500, verbose_name='servicios')),
                ('nombre_consulado', models.CharField(verbose_name='nombre_consulado')),
                ('horarios', models.CharField(verbose_name='horarios')),
            ],
            options={
                'verbose_name_plural': 'Consulados',
            },
        ),
        migrations.AlterField(
            model_name='genealogista',
            name='servicios',
            field=models.CharField(default='Servicios informados', max_length=500, verbose_name='servicios'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='servicios',
            field=models.CharField(default='Servicios informados', max_length=500, verbose_name='servicios'),
        ),
    ]
