# Generated by Django 4.2.2 on 2023-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_consulado_alter_genealogista_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulado',
            name='telefono',
            field=models.CharField(max_length=18, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='genealogista',
            name='telefono',
            field=models.CharField(max_length=18, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefono',
            field=models.CharField(max_length=18, verbose_name='telefono'),
        ),
    ]
